# Generated by Django 2.2.12 on 2023-01-03 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scanantares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanner',
            old_name='nama',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='scanner',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='sortir',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='sortir',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='sortir',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
