# Generated by Django 2.2.12 on 2023-01-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanantares', '0002_auto_20230103_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortir',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
