# Generated by Django 2.2.12 on 2023-01-04 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scanantares', '0005_auto_20230104_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortir',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
