# Generated by Django 4.1.5 on 2023-01-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanantares', '0007_auto_20230104_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortir',
            name='scanner_id',
        ),
        migrations.AddField(
            model_name='sortir',
            name='scanner',
            field=models.CharField(choices=[('angle', 'angle'), ('latif', 'latif'), ('fazza', 'fazza'), ('antarestar', 'antarestar')], max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Scanner',
        ),
    ]
