# Generated by Django 4.1.5 on 2023-01-06 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanantares', '0009_scanner_alter_sortir_scanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortir',
            old_name='scanner',
            new_name='scanner_id',
        ),
    ]
