# Generated by Django 4.1.5 on 2023-01-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanantares', '0013_alter_sortir_scanner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortir',
            old_name='scanner_id',
            new_name='scanner',
        ),
    ]
