# Generated by Django 4.1.5 on 2023-01-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanantares', '0014_rename_scanner_id_sortir_scanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortir',
            name='scanner',
            field=models.CharField(choices=[('angle', 'angle'), ('latif', 'latif'), ('fazza', 'fazza'), ('antarestar', 'antarestar')], max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='Scanner',
        ),
    ]
